version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optee
      MYSQL_USER: optee_user
      MYSQL_PASSWORD: optee_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "9000:9000"
    volumes:
      - ./api:/var/www/html
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optee
      MYSQL_USER: optee_user
      MYSQL_PASSWORD: optee_password

volumes:
  mysql-data:
