version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80" # Expose le port 80 sur votre machine hôte
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # montez votre configuration nginx
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: optee
      MARIADB_USER: optee_user
      MARIADB_PASSWORD: optee_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3001:3001"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: optee
      MARIADB_USER: optee_user
      MARIADB_PASSWORD: optee_password
    volumes:
      - ./api:/app
    depends_on:
      - mysql

volumes:
  mysql-data:
