version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optee
      MYSQL_USER: optee_user
      MYSQL_PASSWORD: optee_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3356:3306"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "3001:3001"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: optee
      MYSQL_USER: optee_user
      MYSQL_PASSWORD: optee_password
    volumes:
      - ./api:/var/www/html
    depends_on:
      - mysql
    command: >
      bash -c "symfony server:start --port=3001"

volumes:
  mysql-data:
